---
title: "Assignment 1 - Patrick Torralba"
author: "Patrick Torralba"
format: 
  html:
    theme: flatly
    fontsize: 0.8em
    code-fold: FALSE
    code-tools: TRUE
    code-copy: TRUE
    toc: TRUE
    toc-depth: 4
    smooth-scroll: TRUE
    embed-resources: TRUE
    fig-align: center
editor: visual
---

# Preliminary

```{r}
#| label: library-import
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  

library(tidyverse)
library(kableExtra)
library(stats)

time <- read_csv("timetrial2026.csv")
```

# Notation

```{r}
#| label: part-a
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  



q1_a <- time |> 
  filter(Id == 6) |> 
  pivot_longer(
    cols = starts_with("Trial"),
    names_to = "Trial",
    values_to = "Time"
  ) |> 
  select(Id, Trial, Time)
```

```{r}
#| label: 1b
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  

vector_y_length <- nrow(time) * 5 #5 represents the number of trials

```

```{r}
#| label: tbl-1c
#| message: FALSE
#| warning: FALSE
#| echo: TRUE 
#| tbl-cap: "Trials Correlation Matrix"

# define covariance matrix; the problem states that diag = 0.05 and off-diag = 0.02, and we also know that each participant must do 5 trials. Meaning this is a 5x5
cov_matrix <- matrix(0.02, nrow = 5, ncol = 5)

diag(cov_matrix) <- 0.05

# Now we convert the covariance matrix to a correlation matrix

corr_matrix <- cov2cor(cov_matrix)

corr_matrix

# Convert the correlation matrix to a table for presentation purposes
`1c_corr_matrix` <-  as_tibble(corr_matrix) |> 
  rename_with(.cols = everything(), ~ str_c("Trials", 1:5, sep = " "))

kable(`1c_corr_matrix`)

```

# Exploratory analysis - changes across trials

```{r}
#| label: fig-2a
#| message: FALSE
#| warning: FALSE
#| echo: TRUE 
#| fig-cap: "Trial Time Distributions" 
#| fig-cap-location: top


time_long <- time |> 
  pivot_longer(
    cols = starts_with("Trial"),
    names_to = "Trial",
    values_to = "Time")

ggplot(time_long, aes(x = Trial, y = Time)) +
  geom_boxplot() +
  labs(
       y = "Time (seconds)")

boxplot.stats(time_long$Time)
```

```{r}
#| label: fig-spaghetti-plot
#| message: FALSE
#| warning: FALSE
#| echo: TRUE 
#| fig-cap: "Individual Trial Trajectories"
#| fig-cap-location: top



ggplot(time_long, aes(x = Trial, y = Time, group = Id, color = Id)) +
  geom_line(color= "steelblue", alpha = 0.3, linewidth = 0.5) +
  labs(
       x = "Trial Number",
       y = "Time (seconds)") 

```

```{r}
#| label: fig-2b
#| message: FALSE
#| warning: FALSE
#| echo: TRUE 
#| fig-cap: "Trial Time Distributions" 
#| fig-cap-location: top


time_long |> 
  filter(Trial == "Trial1" | Trial == "Trial5") |> 
ggplot(aes(x = Trial, y = Time)) +
  geom_boxplot() +
  labs(
       y = "Time (seconds)")

```

```{r}
#| label: fig-2c
#| message: FALSE
#| warning: FALSE
#| echo: TRUE 
#| fig-cap: "Trial Time Distributions by Gender" 
#| fig-cap-location: top


ggplot(time_long, aes(x = Trial, y = Time)) +
  geom_boxplot() +
  facet_wrap(~ Sex)+
  labs(
       y = "Time (seconds)")

Male <- time_long |> 
  filter(Sex == "M")

boxplot.stats(Male$Time)
IQR(Male$Time)

```

# Exploratory analysis - correlation structure

```{r}
#| label: 3a
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  

time |> 
  select(starts_with("Trial")) |> 
  cor() |> 
  round(3) |> 
  kable()

```

# Estimating effects

```{r}
#| label: 4a
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  

t.test(time$Trial5,time$Trial1, alternative = "two.sided", mu = 0, paired = TRUE, conf.level = 0.95)

```

```{r}
#| label: tbl-4bi
#| message: FALSE
#| warning: FALSE
#| echo: TRUE
#| tbl-cap: "Two-Sample t-test results comparing reaction times between men and women per trial"


Trial1_t.test <- t.test(Trial1 ~ Sex, data = time, , conf.level = 0.95)
Trial2_t.test <- t.test(Trial2 ~ Sex, data = time, , conf.level = 0.95)
Trial3_t.test <- t.test(Trial3 ~ Sex, data = time, , conf.level = 0.95)
Trial4_t.test <- t.test(Trial4 ~ Sex, data = time, , conf.level = 0.95)
Trial5_t.test <- t.test(Trial5 ~ Sex, data = time, , conf.level = 0.95)


t_test_results <- tibble(
  Trial = paste0("Trial ", 1:5),

  t_statistic = c(
    Trial1_t.test$statistic,
    Trial2_t.test$statistic,
    Trial3_t.test$statistic,
    Trial4_t.test$statistic,
    Trial5_t.test$statistic
  ),

  df = c(
    Trial1_t.test$parameter,
    Trial2_t.test$parameter,
    Trial3_t.test$parameter,
    Trial4_t.test$parameter,
    Trial5_t.test$parameter
  ),

  p_value = c(
    Trial1_t.test$p.value,
    Trial2_t.test$p.value,
    Trial3_t.test$p.value,
    Trial4_t.test$p.value,
    Trial5_t.test$p.value
  ),

  conf_low = c(
    Trial1_t.test$conf.int[1],
    Trial2_t.test$conf.int[1],
    Trial3_t.test$conf.int[1],
    Trial4_t.test$conf.int[1],
    Trial5_t.test$conf.int[1]
  ),

  conf_high = c(
    Trial1_t.test$conf.int[2],
    Trial2_t.test$conf.int[2],
    Trial3_t.test$conf.int[2],
    Trial4_t.test$conf.int[2],
    Trial5_t.test$conf.int[2]
  ),

  female_estimate = c(
    Trial1_t.test$estimate[1],
    Trial2_t.test$estimate[1],
    Trial3_t.test$estimate[1],
    Trial4_t.test$estimate[1],
    Trial5_t.test$estimate[1]
  ),

  male_estimate = c(
    Trial1_t.test$estimate[2],
    Trial2_t.test$estimate[2],
    Trial3_t.test$estimate[2],
    Trial4_t.test$estimate[2],
    Trial5_t.test$estimate[2]
  )
)


kable(t_test_results)
```

```{r}
#| label: tbl-4bii
#| message: FALSE
#| warning: FALSE
#| echo: TRUE  
#| tbl-cap: "Two Sample t-test results comparing reaction times between men and women"
#| tbl-cap-location: top

time <- time |> 
  mutate(mean_time = rowMeans(pick(starts_with("Trial"))))


bii_t_test_<- t.test(mean_time ~ Sex, data = time, mu = 0, conf.level = 0.95)


t_test_results_2 <- tibble(
  t_statistic = bii_t_test_$statistic,
  df = bii_t_test_$parameter,
  p_value = bii_t_test_$p.value,
  conf_low = bii_t_test_$conf.int[1],
  conf_high = bii_t_test_$conf.int[2],
  female_estimate = bii_t_test_$estimate[1],
  male_estimate = bii_t_test_$estimate[2]
)

kable(t_test_results_2)


```
